#%RAML 0.8
#%RAML 1.0
---
title: Fantasy Player API
baseUri: http://localhost:4242/rest/v1
version: v1

/fantasy:
  /player:
    get:
      description: Retrieves all players
      responses:
        200:
          body:
            applicaion/json:
              example: |
                  {
                    data:{
                       {
                            "f_team":"revature",
                            "firstname":"Ezekiel",
                            "fps":19.68,
                            "lastname":"Elliott",
                            "player_id":16,
                            "position":"RB",
                            "r_team":"DAL"
                            },
                            {
                            "f_team":"revature",
                            "firstname":"Saquon",
                            "fps":20.48,
                            "lastname":"Barkley",
                            "player_id":17,
                            "position":"RB",
                            "r_team":"NYG"
                            },
                            {
                            "f_team":"revature",
                            "firstname":"David",
                            "fps":24.22,
                            "lastname":"Johnson",
                            "player_id":18,
                            "position":"RB",
                            "r_team":"ARI"
                            },
                         }
                        "success": true,
                        "status": 200
                    
                    
                    
                    }
    
  /positon/{postion}:
    get:
      description: Retrieves all player with specified postion
      responses:
        200:
          body:
            application/json:
              example: |
                     {
                        data:{
                            {
                            "f_team":"revature",
                            "firstname":"Ezekiel",
                            "fps":19.68,
                            "lastname":"Elliott",
                            "player_id":16,
                            "position":"RB",
                            "r_team":"DAL"
                            },
                            {
                            "f_team":"revature",
                            "firstname":"Saquon",
                            "fps":20.48,
                            "lastname":"Barkley",
                            "player_id":17,
                            "position":"RB",
                            "r_team":"NYG"
                            },
                            {
                            "f_team":"revature",
                            "firstname":"David",
                            "fps":24.22,
                            "lastname":"Johnson",
                            "player_id":18,
                            "position":"RB",
                            "r_team":"ARI"
                            },
                        },
                      "success": true,
                      "status": 200
              
              
                      }
    
  /individual:
      /{playerName}:
        get:
          description: Retrieves information on individual player
          responses:
              200:
                body:
                  application/json:
                    example: |
                     {
                        data:{ 
                        
                                "f_team":"revature",
                                "firstname":"Andrew",
                                "fps":20.95,
                                "lastname":"Luck",
                                "player_id":12,
                                "position":"QB",
                                "r_team":"IND"
                              },
                              "success": true,
                              "status": 200
                       }
  
  